[project]
name = "cmdsheet"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "alien5516788", email = "93880176+alien5516788@users.noreply.github.com"},
]
dependencies = ["sqlalchemy>=2.0.48", "python-dotenv>=1.2.2", "pywebview[gtk]>=6.1"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.extras]
# Install pywebview extras based on the system manually
# eg: pdm add "pywebview[gtk]>=6.1"
windows = ["pywebview[edgechromium]>=6.1"]
linux = ["pywebview[gtk]>=6.1"]
mac = ["pywebview>=6.1"]

[tool.pdm]
distribution = false

[tool.pdm.scripts]
start = "python3 src/main.py"
build = "python3 build.py"

[dependency-groups]
dev = [
    "pyinstaller>=6.19.0",
]
