[project]
name = "cmdsheet"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "alien5516788", email = "93880176+alien5516788@users.noreply.github.com"},
]
dependencies = ["sqlalchemy>=2.0.48", "python-dotenv>=1.2.2", "pywebview[gtk]>=6.1"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.pdm.scripts]
start = "python3 src/main.py"
build_front = "python3 build.py"
build_exec = "python3 build.py --type=exec" # includes build_front
build_pack = "python3 build.py --type=pack" # includes build_exec

[dependency-groups]
dev = [
    "nuitka[onefile]>=4.0.8",
]
