groups = [
    {"id": "default", "default": "web-exploitation", "count": 10},
    {"id": "recent", "recent": "reverse-engineering", "count": 20},
    {"id": "favourites", "favourites": "docker-workflows", "count": 2},
    {"id": "g1", "name": "web-exploitation", "count": 12},
    {"id": "g2", "name": "reverse-engineering", "count": 8},
    {"id": "g3", "name": "docker-workflows", "count": 5},
    {
        "id": "g4",
        "name": "long-group-name-that-should-truncate-properly",
        "count": 20,
    },
    {"id": "g5", "name": "networking", "count": 6},
    {"id": "g6", "name": "forensics", "count": 3},
    {"id": "g7", "name": "automation-scripts", "count": 14},
    {"id": "g8", "name": "privilege-escalation", "count": 9},
    {"id": "g9", "name": "web-recon", "count": 11},
    {"id": "g10", "name": "api-testing", "count": 7},
    {"id": "g11", "name": "linux-hardening", "count": 4},
    {"id": "g12", "name": "cloud-security", "count": 10},
    {"id": "g13", "name": "malware-analysis", "count": 6},
    {"id": "g14", "name": "osint-tools", "count": 13},
    {"id": "g15", "name": "ci-cd-pipelines", "count": 5},
]


snippets = [
    {
        "id": "1",
        "name": "Docker Commands",
        "description": "Common docker commands for container management and debugging workflows",
        "tags": ["docker", "devops", "containers", "cli", "linux"],
    },
    {
        "id": "2",
        "name": "Reset Git Hard",
        "description": "Force reset git repository to a previous commit. Dangerous but useful.",
        "tags": ["git", "version-control", "danger", "cli"],
    },
    {
        "id": "3",
        "name": "Nmap Scan",
        "description": "Scan target system for open ports and services using aggressive detection flags. It also can do stealth scanning.",
        "tags": [
            "nmap",
            "security",
            "network",
            "recon",
            "pentest",
            "scan",
            "tcp",
            "udp",
            "exploit",
            "enumeration",
            "extra-tag",
        ],
    },
    {
        "id": "4",
        "name": "Check Disk Usage",
        "description": "Display disk usage in a human-readable format",
        "tags": ["linux", "disk", "storage", "cli"],
    },
    {
        "id": "5",
        "name": "Find Running Processes",
        "description": "List all running processes and filter by 'name'",
        "tags": ["linux", "process", "ps", "grep"],
    },
    {
        "id": "6",
        "name": "Kill Process",
        "description": "Terminate a process using its PID",
        "tags": ["linux", "process", "kill", "system"],
    },
    {
        "id": "7",
        "name": "SSH Connection",
        "description": "Connect to a remote server using SSH",
        "tags": ["ssh", "remote", "network", "cli"],
    },
    {
        "id": "8",
        "name": "Download File with Curl",
        "description": "Download files from a URL using curl",
        "tags": ["curl", "download", "http", "cli"],
    },
    {
        "id": "9",
        "name": "Extract Tar File",
        "description": "Extract .tar.gz archive files",
        "tags": ["linux", "tar", "archive", "cli"],
    },
    {
        "id": "10",
        "name": "Search Files",
        "description": "Search for files recursively using find command",
        "tags": ["linux", "find", "search", "filesystem"],
    },
    {
        "id": "15",
        "name": "Git Push",
        "description": "Push local commits to remote repository",
        "tags": ["git", "push", "version-control"],
    },
    {
        "id": "16",
        "name": "Docker Build Image",
        "description": "Build a Docker image from a Dockerfile",
        "tags": ["docker", "build", "containers"],
    },
    {
        "id": "17",
        "name": "Docker Run Container",
        "description": "Run a container from a Docker image",
        "tags": ["docker", "run", "containers"],
    },
    {
        "id": "18",
        "name": "List Docker Containers",
        "description": "List all running Docker containers",
        "tags": ["docker", "ps", "containers"],
    },
    {
        "id": "19",
        "name": "Remove Docker Container",
        "description": "Remove a stopped Docker container",
        "tags": ["docker", "rm", "containers"],
    },
    {
        "id": "20",
        "name": "Ping Host",
        "description": "Check connectivity to a host",
        "tags": ["network", "ping", "diagnostics"],
    },
    {
        "id": "21",
        "name": "Check Uptime",
        "description": "Show how long the system has been running",
        "tags": ["linux", "uptime", "system"],
    },
    {
        "id": "22",
        "name": "Whoami Command",
        "description": "Display current logged-in user",
        "tags": ["linux", "user", "system"],
    },
]
